"""Assemble a Rocq source file stating a Cloq timing theorem.

Cloq proofs are functor-structured: instantiate the CPU (NEORV32) and the program's
RISCVTiming/Automation modules, THEN state `satisfies_all lifted_prog (inv ...) exits t`.
A flat `Require Import Picinae_riscv` is not enough — N, cycle_count_of_trace, R_T0, the
t* timing constants, lifted_prog and exits all live inside the instantiated modules.

For the smoke target we reuse the vendored program (riscv_addloop_timing_proof.v's
Program_addloop) via the functor; the agent supplies only the invariant body.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass
class TargetSpec:
    name: str
    requires: list[str]
    lifted_program: str
    entry_addr: int
    exit_point: str
    theorem_name: str
    params: list[tuple[str, str]]


# The smoke template reuses the vendored Program_addloop by instantiating TimingProof.
# The theorem statement mirrors the vendored addloop_timing binders so a gold proof applies.
PROOF_TEMPLATE = """\
(* AUTO-GENERATED by cloq-agent.theorem_builder. Do not edit by hand. *)
Require Import NArith.
Require Import Picinae_riscv.
Require Import RISCVTiming. Import RISCVNotations.
Require Import riscv_addloop_timing_proof.

(* Reuse the vendored program (Program_addloop) by instantiating its functor;
   state the agent's theorem in the SAME scope so Picinae primitives (startof,
   models, rvtypctx) and functor members (lifted_prog, exits) are all visible. *)
Module {thm}_Proof (cpu : RVCPUTimingBehavior).

  Module Inner := TimingProof cpu.
  Import Inner.

{invariant}

  Theorem {thm} :
    forall s t s' x' {binders}
      (ENTRY: startof t (x',s') = (Addr entry_addr, s))
      (MDL: models rvtypctx s)
      (T0: s R_T0 = x)
      (T1: s R_T1 = y),
    satisfies_all lifted_prog ({inv_name} {inv_args}) exits ((x',s') :: t).
  Proof.
    {proof_body}
  Qed.

End {thm}_Proof.

Module NRV32 := NEORV32 NEORV32BaseConfig.
Module {thm}_NRV32 := {thm}_Proof NRV32.
"""

def _binders(params: list[tuple[str, str]]) -> str:
    if not params:
        return ""
    return " ".join(f"({n} : {ty})" for n, ty in params)


def _inv_args(params: list[tuple[str, str]]) -> str:
    return " ".join(n for n, _ in params)


def render(
    spec: TargetSpec,
    invariant_def: str,
    invariant_name: str,
    proof_body: str = "Admitted.",
) -> str:
    return PROOF_TEMPLATE.format(
        invariant=invariant_def.strip(),
        thm=spec.theorem_name,
        binders=_binders(spec.params),
        inv_name=invariant_name,
        inv_args=_inv_args(spec.params),
        proof_body=proof_body.strip(),
    )


def write(spec: TargetSpec, source: str, workspace: Path) -> Path:
    out = Path(workspace) / "targets" / f"{spec.name.capitalize()}_gen.v"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(source)
    return out
