"""Assemble a Rocq source file stating a Cloq timing theorem for a given target.

A Cloq timing proof has a fixed skeleton (from the paper): require the lifted code + Cloq
timing modules, define an invariant set `timing_invs` over (address -> state proposition),
then state `satisfies_all lifted_code (timing_invs ...) <exit> t`. The agent's creative output
is the *body* of `timing_invs`; everything around it is boilerplate this module emits.

We write a self-contained `.v` into the proofs workspace so petanque can `start` it. The
invariant body is supplied by the agent (or taken from a gold file for the smoke target).
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass
class TargetSpec:
    name: str                 # e.g. "addloop"
    requires: list[str]       # Rocq modules to Require Import (lifted code + Cloq timing libs)
    lifted_program: str       # the Gallina identifier of the lifted program map
    entry_addr: int
    exit_point: str           # name of the exit predicate, e.g. "addloop_exit"
    theorem_name: str         # e.g. "addloop_timing"
    # free parameters universally quantified in the theorem (name, Rocq type)
    params: list[tuple[str, str]]


PROOF_TEMPLATE = """\
(* AUTO-GENERATED by cloq-agent.theorem_builder. Do not edit by hand. *)
{requires}

{invariant}

Theorem {thm} :
  forall {binders} (t : trace),
  satisfies_all {prog} ({inv_name} {inv_args}) {exit} t.
Proof.
  {proof_body}
Qed.
"""


def _binders(params: list[tuple[str, str]]) -> str:
    if not params:
        return ""
    return " ".join(f"({n} : {ty})" for n, ty in params)


def _inv_args(params: list[tuple[str, str]]) -> str:
    return " ".join(n for n, _ in params)


def render(
    spec: TargetSpec,
    invariant_def: str,
    invariant_name: str,
    proof_body: str = "Admitted (* filled by the agent loop *).",
) -> str:
    """Render the full .v source. `invariant_def` is a complete `Definition timing_invs ...`."""
    requires = "\n".join(f"Require Import {m}." for m in spec.requires)
    return PROOF_TEMPLATE.format(
        requires=requires,
        invariant=invariant_def.strip(),
        thm=spec.theorem_name,
        binders=_binders(spec.params),
        prog=spec.lifted_program,
        inv_name=invariant_name,
        inv_args=_inv_args(spec.params),
        exit=spec.exit_point,
        proof_body=proof_body.strip(),
    )


def write(spec: TargetSpec, source: str, workspace: Path) -> Path:
    """Write the rendered source into the workspace and return its path."""
    out = Path(workspace) / "targets" / f"{spec.name.capitalize()}_gen.v"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(source)
    return out
