(* AUTO-GENERATED by cloq-agent.theorem_builder. Do not edit by hand. *)
Require Import NArith.
Require Import Picinae_riscv.
Require Import NEORV32.
Require Import RISCVTiming.
Require Import riscv_addloop_timing_proof.
Import RISCVNotations.

(* Reuse the vendored program (Program_addloop) by instantiating its functor;
   state the agent's theorem in the SAME scope so Picinae primitives (startof,
   models, rvtypctx) and functor members (lifted_prog, exits) are all visible. *)
Module addloop_timing_gen_Proof (cpu : RVCPUTimingBehavior).

  Module Inner := TimingProof cpu.
  Import Inner.
  (* Import Inner alone only exposes Inner's *direct* members; the Picinae
     primitives (startof/models/rvtypctx) and the functor outputs
     (lifted_prog/exits/entry_addr/cycle_count_of_trace + the t* timing
     constants) live in these instantiated submodules and are otherwise
     invisible at the theorem's scope. *)
  Import Inner.RISCVTiming.
  Import Inner.Program_addloop.
  Import Inner.addloopAuto.

Definition addloop_llm_timing_invs (x y : N) (t:trace) :=
match t with (Addr a, s) :: t' => match a with
    | 0x8  => Some (s R_T0 = x /\ s R_T1 = y /\
        cycle_count_of_trace t' = 0)
    | 0x10 => Some (s R_T2 = 1 /\ s R_T3 = 0 /\ 
        s R_T0 <= x /\
        cycle_count_of_trace t' = 
            (x - s R_T0) * (tbeq + taddi + tsub + ttbeq))
    | 0x20 => Some (cycle_count_of_trace t' = 0)
    | _ => None end
  | _ => None end.

  Theorem addloop_timing_gen :
    forall s t s' x' (x : N) (y : N)
      (ENTRY: startof t (x',s') = (Addr entry_addr, s))
      (MDL: models rvtypctx s)
      (T0: s R_T0 = x)
      (T1: s R_T1 = y),
    satisfies_all lifted_prog (addloop_llm_timing_invs x y) exits ((x',s') :: t).
  Proof.
    Admitted.

End addloop_timing_gen_Proof.

Module addloop_timing_gen_CPU := NEORV32 NEORV32BaseConfig.
Module addloop_timing_gen_Concrete := addloop_timing_gen_Proof addloop_timing_gen_CPU.
