(* AUTO-GENERATED by cloq-agent.lift.intake from compiled C. Do not edit by hand. *)
Require Import RISCVTiming.
Import RISCVNotations.

Module TimingProof (cpu : RVCPUTimingBehavior).

  Module Program_ap_sum_u32 <: ProgramInformation.
    Definition entry_addr : N := 0x0.

    Definition exits (t:trace) : bool :=
      match t with (Addr a, _) :: _ => match a with
        | 0x24 => true
        | 0x2c => true
        | _ => false
        end | _ => false end.

    Definition binary (a : addr) : N :=
      match a with
        | 0x0 => 0x02058463 (* beq a1,zero,28 <.L4>  *)
        | 0x4 => 0x00259593 (* slli a1,a1,0x2  *)
        | 0x8 => 0x00050793 (* addi a5,a0,0  *)
        | 0xc => 0x00b506b3 (* add a3,a0,a1  *)
        | 0x10 => 0x00000513 (* addi a0,zero,0  *)
        | 0x14 => 0x0007a703 (* lw a4,0(a5)  *)
        | 0x18 => 0x00478793 (* addi a5,a5,4  *)
        | 0x1c => 0x00e50533 (* add a0,a0,a4  *)
        | 0x20 => 0xfed79ae3 (* bne a5,a3,14 <.L3>  *)
        | 0x24 => 0x00008067 (* jalr zero,0(ra)  *)
        | 0x28 => 0x00000513 (* addi a0,zero,0  *)
        | 0x2c => 0x00008067 (* jalr zero,0(ra)  *)
        | 0x30 => 0x02058263 (* beq a1,zero,54 <.L10>  *)
        | 0x34 => 0x00050793 (* addi a5,a0,0  *)
        | 0x38 => 0x00b505b3 (* add a1,a0,a1  *)
        | 0x3c => 0x00000513 (* addi a0,zero,0  *)
        | 0x40 => 0x0007c703 (* lbu a4,0(a5)  *)
        | 0x44 => 0x00178793 (* addi a5,a5,1  *)
        | 0x48 => 0x00e50533 (* add a0,a0,a4  *)
        | 0x4c => 0xfeb79ae3 (* bne a5,a1,40 <.L9>  *)
        | 0x50 => 0x00008067 (* jalr zero,0(ra)  *)
        | 0x54 => 0x00000513 (* addi a0,zero,0  *)
        | 0x58 => 0x00008067 (* jalr zero,0(ra)  *)
        | 0x5c => 0x02058063 (* beq a1,zero,7c <.L12>  *)
        | 0x60 => 0x00259593 (* slli a1,a1,0x2  *)
        | 0x64 => 0x00b50733 (* add a4,a0,a1  *)
        | 0x68 => 0x00052783 (* lw a5,0(a0)  *)
        | 0x6c => 0x00450513 (* addi a0,a0,4  *)
        | 0x70 => 0x02c787b3 (* mul a5,a5,a2  *)
        | 0x74 => 0xfef52e23 (* sw a5,-4(a0)  *)
        | 0x78 => 0xfee518e3 (* bne a0,a4,68 <.L14>  *)
        | 0x7c => 0x00008067 (* jalr zero,0(ra)  *)
        | 0x80 => 0x02060a63 (* beq a2,zero,b4 <.L22>  *)
        | 0x84 => 0x00261613 (* slli a2,a2,0x2  *)
        | 0x88 => 0x00050793 (* addi a5,a0,0  *)
        | 0x8c => 0x00c50633 (* add a2,a0,a2  *)
        | 0x90 => 0x00000513 (* addi a0,zero,0  *)
        | 0x94 => 0x0007a703 (* lw a4,0(a5)  *)
        | 0x98 => 0x0005a683 (* lw a3,0(a1)  *)
        | 0x9c => 0x00478793 (* addi a5,a5,4  *)
        | 0xa0 => 0x00458593 (* addi a1,a1,4  *)
        | 0xa4 => 0x02d70733 (* mul a4,a4,a3  *)
        | 0xa8 => 0x00e50533 (* add a0,a0,a4  *)
        | 0xac => 0xfec794e3 (* bne a5,a2,94 <.L21>  *)
        | 0xb0 => 0x00008067 (* jalr zero,0(ra)  *)
        | 0xb4 => 0x00000513 (* addi a0,zero,0  *)
        | 0xb8 => 0x00008067 (* jalr zero,0(ra)  *)
        | 0xbc => 0x00050793 (* addi a5,a0,0  *)
        | 0xc0 => 0x02058263 (* beq a1,zero,e4 <.L27>  *)
        | 0xc4 => 0x00000713 (* addi a4,zero,0  *)
        | 0xc8 => 0x00000513 (* addi a0,zero,0  *)
        | 0xcc => 0x0007a683 (* lw a3,0(a5)  *)
        | 0xd0 => 0x00170713 (* addi a4,a4,1  *)
        | 0xd4 => 0x00478793 (* addi a5,a5,4  *)
        | 0xd8 => 0x00d50533 (* add a0,a0,a3  *)
        | 0xdc => 0xfee598e3 (* bne a1,a4,cc <.L26>  *)
        | 0xe0 => 0x00008067 (* jalr zero,0(ra)  *)
        | 0xe4 => 0x00000513 (* addi a0,zero,0  *)
        | 0xe8 => 0x00008067 (* jalr zero,0(ra)  *)
        | 0xec => 0x02058063 (* beq a1,zero,10c <.L29>  *)
        | 0xf0 => 0x00259593 (* slli a1,a1,0x2  *)
        | 0xf4 => 0x00b50733 (* add a4,a0,a1  *)
        | 0xf8 => 0x00052783 (* lw a5,0(a0)  *)
        | 0xfc => 0x00450513 (* addi a0,a0,4  *)
        | 0x100 => 0x00c7c7b3 (* xor a5,a5,a2  *)
        | 0x104 => 0xfef52e23 (* sw a5,-4(a0)  *)
        | 0x108 => 0xfee518e3 (* bne a0,a4,f8 <.L31>  *)
        | 0x10c => 0x00008067 (* jalr zero,0(ra)  *)
        | _ => 0
      end.
  End Program_ap_sum_u32.

  Module RISCVTiming := RISCVTiming cpu Program_ap_sum_u32.
  Module ap_sum_u32Auto := RISCVTimingAutomation RISCVTiming.
  Import Program_ap_sum_u32 ap_sum_u32Auto.

End TimingProof.
