(* AUTO-GENERATED by cloq-agent.theorem_builder. Do not edit by hand. *)
Require Import NArith.
Require Import Picinae_riscv.
Require Import NEORV32.
Require Import RISCVTiming.
Require Import ap_sum_u32_lifted.
Import RISCVNotations.

(* Reuse the vendored program (Program_ap_sum_u32) by instantiating its functor;
   state the agent's theorem in the SAME scope so Picinae primitives (startof,
   models, rvtypctx) and functor members (lifted_prog, exits) are all visible. *)
Module ap_sum_u32_timing_gen_Proof (cpu : RVCPUTimingBehavior).

  Module Inner := TimingProof cpu.
  Import Inner.
  (* Import Inner alone only exposes Inner's *direct* members; the Picinae
     primitives (startof/models/rvtypctx) and the functor outputs
     (lifted_prog/exits/entry_addr/cycle_count_of_trace + the t* timing
     constants) live in these instantiated submodules and are otherwise
     invisible at the theorem's scope. *)
  Import Inner.RISCVTiming.
  Import Inner.Program_ap_sum_u32.
  Import Inner.ap_sum_u32Auto.

Definition ap_sum_u32_timing_invs (arr len : N) (t:trace) : option Prop :=
match t with (Addr a, s) :: t' => match a with
| 0x0 => Some (s R_A0 = arr /\ s R_A1 = len /\ 4 * len < 2^32 /\ (exists k, arr = 4 * k) /\ cycle_count_of_trace t' = 0)
| 0x14 => Some (exists i, i < len /\ 4 * len < 2^32 /\ s R_A5 = arr ⊕ (4 * i) /\ s R_A3 = arr ⊕ (4 * len) /\
        cycle_count_of_trace t' = tfbeq + tslli 2 + taddi + tadd + taddi + i * (tlw + taddi + tadd + ttbne))
| 0x24 => Some (cycle_count_of_trace t' = tfbeq + tslli 2 + taddi + tadd + taddi + (len - 1) * (tlw + taddi + tadd + ttbne) + (tlw + taddi + tadd + tfbne))
| 0x2c => Some (cycle_count_of_trace t' = taddi + ttbeq)
| _ => None end | _ => None end.

  Theorem ap_sum_u32_timing_gen :
    forall s t s' x' (arr : N) (len : N)
      (ENTRY: startof t (x',s') = (Addr entry_addr, s))
      (MDL: models rvtypctx s)
      (A0: s R_A0 = arr)
      (A1: s R_A1 = len)
      (LEN_VALID: 4 * len < 2^32)
      (PTR_ALIGN: exists k, arr = 4 * k),
    satisfies_all lifted_prog (ap_sum_u32_timing_invs arr len) exits ((x',s') :: t).
  Proof.
    Admitted.

End ap_sum_u32_timing_gen_Proof.

Module ap_sum_u32_timing_gen_CPU := NEORV32 NEORV32BaseConfig.
Module ap_sum_u32_timing_gen_Concrete := ap_sum_u32_timing_gen_Proof ap_sum_u32_timing_gen_CPU.
