(* AUTO-GENERATED by cloq-agent.theorem_builder. Do not edit by hand. *)
Require Import NArith.
Require Import Picinae_riscv.
Require Import NEORV32.
Require Import RISCVTiming.
Require Import ct_swap_proof.
Import RISCVNotations.

(* Reuse the vendored program (Program_ct_swap) by instantiating its functor;
   state the agent's theorem in the SAME scope so Picinae primitives (startof,
   models, rvtypctx) and functor members (lifted_prog, exits) are all visible. *)
Module ct_swap_timing_gen_Proof (cpu : RVCPUTimingBehavior).

  Module Inner := TimingProof cpu.
  Import Inner.
  (* Import Inner alone only exposes Inner's *direct* members; the Picinae
     primitives (startof/models/rvtypctx) and the functor outputs
     (lifted_prog/exits/entry_addr/cycle_count_of_trace + the t* timing
     constants) live in these instantiated submodules and are otherwise
     invisible at the theorem's scope. *)
  Import Inner.RISCVTiming.
  Import Inner.Program_ct_swap.
  Import Inner.ct_swapAuto.

Definition ct_swap_timing_invs (len : N) (base_addr_b : N) (t:trace) : option Prop :=
match t with (Addr a, s) :: t' => match a with
| 0x1e4 => Some (
        (4 * len < 2^32) /\
        (* The pointer to uint32_t array b is a multiple of 4. *)
        (exists k', base_addr_b = 4 * k') /\
        (s R_A3 = len) /\
        (s R_A2 = base_addr_b) /\
        (cycle_count_of_trace t' = 0)
    )
| 0x1f0 => Some (
        (4 * len < 2^32) /\
        (* The pointer to uint32_t array b is a multiple of 4.  *)
        (exists k', base_addr_b = 4 * k') /\
        (* Pointer b is incremented by 4 until it reaches the value in R_A3 *)
        (s R_A3 = (base_addr_b ⊕ (4 * len))) /\
        (* The pointer in R_A2 is the base pointer of b modulo plus the offset index * 4. *)
        (exists index, 
            (index <= len) /\
            (s R_A2 = base_addr_b ⊕ (4 * index)) /\  
            (cycle_count_of_trace t' =
                tslli 2 + tsub + tadd + 
                (* array loop iteration *)
                (index *
                    (ttbne + tlw + tlw + taddi + taddi + txor + tand + txor + tsw + tlw + txor + tsw + tjal)
                )
            )
        )
    )
| 0x1f4 => Some (
        time_of_ct_swap len t
    )
| _ => None end | _ => None end.

  Theorem ct_swap_timing_gen :
    forall s t s' x' (len : N) (base_addr_b : N)
      (ENTRY: startof t (x',s') = (Addr entry_addr, s))
      (MDL: models rvtypctx s)
      (A3: s R_A3 = len)
      (A2: s R_A2 = base_addr_b)
      (PTR_ALIGN: exists k', base_addr_b = 4 * k')
      (LEN_VALID: 4 * len < 2^32),
    satisfies_all lifted_prog (ct_swap_timing_invs len base_addr_b) exits ((x',s') :: t).
  Proof.
    Admitted.

End ct_swap_timing_gen_Proof.

Module ct_swap_timing_gen_CPU := NEORV32 NEORV32BaseConfig.
Module ct_swap_timing_gen_Concrete := ct_swap_timing_gen_Proof ct_swap_timing_gen_CPU.
