(* AUTO-GENERATED by cloq-agent.theorem_builder. Do not edit by hand. *)
Require Import NArith.
Require Import Picinae_riscv.
Require Import NEORV32.
Require Import array.
Require Import RISCVTiming.
Require Import find_in_array_proof.
Import RISCVNotations.

(* Reuse the vendored program (Program_find_in_array) by instantiating its functor;
   state the agent's theorem in the SAME scope so Picinae primitives (startof,
   models, rvtypctx) and functor members (lifted_prog, exits) are all visible. *)
Module find_in_array_timing_gen_Proof (cpu : RVCPUTimingBehavior).

  Module Inner := TimingProof cpu.
  Import Inner.
  (* Import Inner alone only exposes Inner's *direct* members; the Picinae
     primitives (startof/models/rvtypctx) and the functor outputs
     (lifted_prog/exits/entry_addr/cycle_count_of_trace + the t* timing
     constants) live in these instantiated submodules and are otherwise
     invisible at the theorem's scope. *)
  Import Inner.RISCVTiming.
  Import Inner.Program_find_in_array.
  Import Inner.find_in_arrayAuto.

Definition timing_invs (base_mem : memory) (arr : N) (key : N) (len : N) (t:trace) :=
match t with (Addr a, s) :: t' => match a with
| 0x1e4 => Some (s V_MEM32 = base_mem /\ s R_A0 = arr /\ s R_A1 = key /\ 
            s R_A2 = len /\ 4 * len <= 2^32 - 1 /\
            cycle_count_of_trace t' = 0)
| 0x1e8 => Some (s V_MEM32 = base_mem /\ s R_A0 = arr /\ s R_A1 = key /\ 
            s R_A2 = len /\ s R_A5 = 0 /\
            cycle_count_of_trace t' = (len - s R_A5) * (taddi + tlw + tbeq + tjal + taddi) + taddi + tlw + tbeq + tjal)
| 0x204 => Some (s V_MEM32 = base_mem /\ s R_A0 = arr /\ s R_A1 = key /\ 
            s R_A2 = len /\ s R_A5 = len /\
            cycle_count_of_trace t' = (len - s R_A5) * (taddi + tlw + tbeq + tjal + taddi) + taddi + tlw + tbeq + tjal)
| 0x208 => Some (timing_postcondition base_mem arr key len t)
| _ => None
end | _ => None end.

  Theorem find_in_array_timing_gen :
    forall s t s' x' (base_mem : memory) (arr : N) (key : N) (len : N)
      (ENTRY: startof t (x',s') = (Addr entry_addr, s))
      (MDL: models rvtypctx s)
      (A0: s R_A0 = arr)
      (A1: s R_A1 = key)
      (A2: s R_A2 = len)
      (MEM: s V_MEM32 = base_mem)
      (LEN_VALID: 4 * len <= 2^32 - 1),
    satisfies_all lifted_prog (timing_invs base_mem arr key len) exits ((x',s') :: t).
  Proof.
    Admitted.

End find_in_array_timing_gen_Proof.

Module find_in_array_timing_gen_CPU := NEORV32 NEORV32BaseConfig.
Module find_in_array_timing_gen_Concrete := find_in_array_timing_gen_Proof find_in_array_timing_gen_CPU.
