(* AUTO-GENERATED by cloq-agent.theorem_builder. Do not edit by hand. *)
Require Import NArith.
Require Import Picinae_riscv.
Require Import RISCVTiming. Import RISCVNotations.
Require Import riscv_addloop_timing_proof.

(* Reuse the vendored program (Program_addloop) by instantiating its functor;
   state the agent's theorem in the SAME scope so Picinae primitives (startof,
   models, rvtypctx) and functor members (lifted_prog, exits) are all visible. *)
Module addloop_timing_gen_Proof (cpu : RVCPUTimingBehavior).

  Module Inner := TimingProof cpu.
  Import Inner.

Definition timing_invs (x y : N) (t:trace) :=
match t with (Addr a, s) :: t' => match a with
| 0x0  => Some (s R_T0 = x /\ s R_T1 = y /\
        cycle_count_of_trace t' = 
            tori + tandi + (x - s R_T0) * (tfbeq + taddi + tsub + ttbeq))
| 0x10 => Some (s R_T2 = 1 /\ s R_T3 = 0 /\
        s R_T0 <= x /\
        cycle_count_of_trace t' = 
            tori + tandi + (x - s R_T0) * (tfbeq + taddi + tsub + ttbeq))
| _ => None end | _ => None end.

  Theorem addloop_timing_gen :
    forall s t s' x' (x : N) (y : N)
      (ENTRY: startof t (x',s') = (Addr entry_addr, s))
      (MDL: models rvtypctx s)
      (T0: s R_T0 = x)
      (T1: s R_T1 = y),
    satisfies_all lifted_prog (timing_invs x y) exits ((x',s') :: t).
  Proof.
    Admitted.
  Qed.

End addloop_timing_gen_Proof.

Module NRV32 := NEORV32 NEORV32BaseConfig.
Module addloop_timing_gen_NRV32 := addloop_timing_gen_Proof NRV32.
