(* AUTO-GENERATED by cloq-agent.theorem_builder. Do not edit by hand. *)
Require Import NArith.
Require Import Picinae_riscv.
Require Import NEORV32.
Require Import RISCVTiming.
Require Import se_find_eq_lifted.
Import RISCVNotations.

(* Reuse the vendored program (Program_se_find_eq) by instantiating its functor;
   state the agent's theorem in the SAME scope so Picinae primitives (startof,
   models, rvtypctx) and functor members (lifted_prog, exits) are all visible. *)
Module se_find_eq_timing_gen_Proof (cpu : RVCPUTimingBehavior).

  Module Inner := TimingProof cpu.
  Import Inner.
  (* Import Inner alone only exposes Inner's *direct* members; the Picinae
     primitives (startof/models/rvtypctx) and the functor outputs
     (lifted_prog/exits/entry_addr/cycle_count_of_trace + the t* timing
     constants) live in these instantiated submodules and are otherwise
     invisible at the theorem's scope. *)
  Import Inner.RISCVTiming.
  Import Inner.Program_se_find_eq.
  Import Inner.se_find_eqAuto.

  Definition cloq_key_in_array (mem : memory) (arr : addr) (key : N) (len : N) : Prop :=
      exists i, i < len /\ mem Ⓓ[arr + (4 * i)] = key.

  Lemma cloq_lt_impl_lt_or_eq : forall x y, x < 1 + y -> x = y \/ x < y.
  Proof. lia. Qed.

  Definition cloq_N_peano_ind_Set (P : N -> Set) := N.peano_rect P.

  Fixpoint cloq_key_in_array_dec (mem : memory) (arr : addr) (key len : N)
          : {cloq_key_in_array mem arr key len} + {~ cloq_key_in_array mem arr key len}.
      induction len using cloq_N_peano_ind_Set.
      - right. intro. destruct H as (idx & Contra & _). lia.
      - destruct IHlen as [IN | NOT_IN].
          -- left. destruct IN as (idx & Lt & Eq). exists idx. split. lia. assumption.
          -- destruct (N.eq_dec (mem Ⓓ[arr + (4 * len)]) key).
              + left. exists len. split. lia. assumption.
              + right. intro. destruct H as (idx & Lt & Eq).
                  assert (idx = len). {
                  destruct (cloq_lt_impl_lt_or_eq idx len). lia.
                      subst. reflexivity.
                  exfalso. apply NOT_IN. exists idx. now split.
                  } subst. contradiction.
  Qed.

  Definition cloq_time_of_se_find_eq (len : N) (found_idx : option N) (t : trace) :=
      cycle_count_of_trace t =
      match found_idx with
      | Some i => taddi + taddi + tfbeq + taddi + tjal + i * (tlw + taddi + ttbne + taddi + tfbeq) + tlw + taddi + tfbne + taddi + tjalr
      | None => match len with
                | 0 => taddi + taddi + ttbeq + tjalr
                | _ => taddi + taddi + tfbeq + taddi + tjal + (len - 1) * (tlw + taddi + ttbne + taddi + tfbeq) + tlw + taddi + ttbne + taddi + ttbeq + tjalr
                end
      end.

  Definition cloq_timing_postcondition (mem : memory) (arr : addr) (key : N) (len : N)
          (t : trace) : Prop :=
      (exists i, i < len /\ mem Ⓓ[arr + (4 * i)] = key /\
          (forall j, j < i -> mem Ⓓ[arr + (4 * j)] <> key) /\
          cloq_time_of_se_find_eq len (Some i) t) \/
      ((~ exists i, i < len /\ mem Ⓓ[arr + (4 * i)] = key) /\
          cloq_time_of_se_find_eq len None t).

Definition se_find_eq_timing_invs (arr key len : N) (base_mem : memory) (t:trace) : option Prop :=
match t with (Addr a, s) :: t' => match a with
| 0x0 => Some (s V_MEM32 = base_mem /\ s R_A0 = arr /\ s R_A1 = key /\ s R_A2 = len /\ (4 * len < 2^32) /\ (exists k', arr = 4 * k') /\ cycle_count_of_trace t' = 0)
| 0x1c => Some (exists i, i < len /\ s R_A4 = i /\ s R_A5 = arr ⊕ (4 * i) /\ s R_A1 = key /\ s R_A0 = len /\ s R_A2 = len /\ s V_MEM32 = base_mem /\ (forall j, j < i -> base_mem Ⓓ[arr ⊕ (4 * j)] <> key) /\ cycle_count_of_trace t' = taddi + taddi + tfbeq + taddi + tjal + i * (tlw + taddi + ttbne + taddi + tfbeq))
| 0x2c => Some (cloq_timing_postcondition base_mem arr key len t)
| 0x30 => Some (cloq_timing_postcondition base_mem arr key len t)
| _ => None end | _ => None end.

  Theorem se_find_eq_timing_gen :
    forall s t s' x' (arr : N) (key : N) (len : N) (base_mem : memory)
      (ENTRY: startof t (x',s') = (Addr entry_addr, s))
      (MDL: models rvtypctx s)
      (A0: s R_A0 = arr)
      (A1: s R_A1 = key)
      (A2: s R_A2 = len)
      (MEM: s V_MEM32 = base_mem)
      (LEN_VALID: 4 * len < 2^32)
      (PTR_ALIGN: exists k', arr = 4 * k'),
    satisfies_all lifted_prog (se_find_eq_timing_invs arr key len base_mem) exits ((x',s') :: t).
  Proof.
    Local Ltac step := tstep r5_step.
    intros.
    apply prove_invs.
    simpl. rewrite ENTRY. unfold entry_addr. now step.
    intros.
    eapply startof_prefix in ENTRY; try eassumption.
    eapply preservation_exec_prog in MDL; try eassumption; [idtac|apply lift_riscv_welltyped].
    clear - ENTRY PRE MDL. rename t1 into t. rename s1 into s'.
    destruct_inv 32 PRE.
