(* AUTO-GENERATED by cloq-agent.lift.intake from compiled C. Do not edit by hand. *)
Require Import RISCVTiming.
Import RISCVNotations.

Module TimingProof (cpu : RVCPUTimingBehavior).

  Module Program_se_find_ge <: ProgramInformation.
    Definition entry_addr : N := 0x0.

    Definition exits (t:trace) : bool :=
      match t with (Addr a, _) :: _ => match a with
        | 0x2c => true
        | 0x30 => true
        | _ => false
        end | _ => false end.

    Definition binary (a : addr) : N :=
      match a with
        | 0x0 => 0x00050793 (* addi a5,a0,0  *)
        | 0x4 => 0x00060513 (* addi a0,a2,0  *)
        | 0x8 => 0x02060263 (* beq a2,zero,2c <.L2>  *)
        | 0xc => 0x00000713 (* addi a4,zero,0  *)
        | 0x10 => 0x00c0006f (* jal zero,1c <.L3>  *)
        | 0x14 => 0x00170713 (* addi a4,a4,1  *)
        | 0x18 => 0x00e50c63 (* beq a0,a4,30 <.L10>  *)
        | 0x1c => 0x0007a683 (* lw a3,0(a5)  *)
        | 0x20 => 0x00478793 (* addi a5,a5,4  *)
        | 0x24 => 0xfeb6e8e3 (* bltu a3,a1,14 <.L11>  *)
        | 0x28 => 0x00070513 (* addi a0,a4,0  *)
        | 0x2c => 0x00008067 (* jalr zero,0(ra)  *)
        | 0x30 => 0x00008067 (* jalr zero,0(ra)  *)
        | _ => 0
      end.
  End Program_se_find_ge.

  Module RISCVTiming := RISCVTiming cpu Program_se_find_ge.
  Module se_find_geAuto := RISCVTimingAutomation RISCVTiming.
  Import Program_se_find_ge se_find_geAuto.

End TimingProof.
