(* AUTO-GENERATED by cloq-agent.theorem_builder. Do not edit by hand. *)
Require Import NArith.
Require Import Picinae_riscv.
Require Import NEORV32.
Require Import RISCVTiming.
Require Import uxListRemove.
Import RISCVNotations.

(* Reuse the vendored program (Program_uxListRemove) by instantiating its functor;
   state the agent's theorem in the SAME scope so Picinae primitives (startof,
   models, rvtypctx) and functor members (lifted_prog, exits) are all visible. *)
Module uxListRemove_timing_gen_Proof (cpu : RVCPUTimingBehavior).

  Module Inner := TimingProof cpu.
  Import Inner.
  (* Import Inner alone only exposes Inner's *direct* members; the Picinae
     primitives (startof/models/rvtypctx) and the functor outputs
     (lifted_prog/exits/entry_addr/cycle_count_of_trace + the t* timing
     constants) live in these instantiated submodules and are otherwise
     invisible at the theorem's scope. *)
  Import Inner.RISCVTiming.
  Import Inner.Program_uxListRemove.
  Import Inner.uxListRemoveAuto.

Definition timing_invs (base_mem : memory) (a0 : N) (t:trace) :=
match t with (Addr a, s) :: t' => match a with
| 0x80002440 => Some (s R_A0 = a0 /\ s V_MEM32 = base_mem /\
                        noverlaps base_mem a0 /\
                        cycle_count_of_trace t' = 0)
| 0x80002460 => Some (noverlaps (s V_MEM32) a0 /\
                        cycle_count_of_trace t' = tlw + tlw + tlw + tsw + tsw + tlw +
                        (if s V_MEM32 Ⓓ[4 + s V_MEM32 Ⓓ[16 + a0]] =? a0 then
                            tfbne + tsw 
                         else
                            ttbne) +
                        tsw + tlw + taddi + tsw + tjalr)
| 0x80002470 => Some (time_of_uxListRemove t base_mem a0)
| _ => None
end | _ => None end.

  Theorem uxListRemove_timing_gen :
    forall s t s' x' (base_mem : memory) (a0 : N)
      (ENTRY: startof t (x',s') = (Addr entry_addr, s))
      (MDL: models rvtypctx s)
      (A0: s R_A0 = a0)
      (NVL: create_noverlaps (memory_regions base_mem a0))
      (MEM: s V_MEM32 = base_mem),
    satisfies_all lifted_prog (timing_invs base_mem a0) exits ((x',s') :: t).
  Proof.
    Admitted.

End uxListRemove_timing_gen_Proof.

Module uxListRemove_timing_gen_CPU := NEORV32 NEORV32BaseConfig.
Module uxListRemove_timing_gen_Concrete := uxListRemove_timing_gen_Proof uxListRemove_timing_gen_CPU.
