(* AUTO-GENERATED by cloq-agent.theorem_builder. Do not edit by hand. *)
Require Import NArith.
Require Import Picinae_riscv.
Require Import NEORV32.
Require Import RISCVTiming.
Require Import vListInitialiseItem.
Import RISCVNotations.

(* Reuse the vendored program (Program_vListInitialiseItem) by instantiating its functor;
   state the agent's theorem in the SAME scope so Picinae primitives (startof,
   models, rvtypctx) and functor members (lifted_prog, exits) are all visible. *)
Module vListInitialiseItem_timing_gen_Proof (cpu : RVCPUTimingBehavior).

  Module Inner := TimingProof cpu.
  Import Inner.
  (* Import Inner alone only exposes Inner's *direct* members; the Picinae
     primitives (startof/models/rvtypctx) and the functor outputs
     (lifted_prog/exits/entry_addr/cycle_count_of_trace + the t* timing
     constants) live in these instantiated submodules and are otherwise
     invisible at the theorem's scope. *)
  Import Inner.RISCVTiming.
  Import Inner.Program_vListInitialiseItem.
  Import Inner.vListInitialiseItemAuto.

Definition timing_invs (base_mem : memory) (a0 : N) (t:trace) :=
match t with (Addr a, s) :: t' => match a with
| 0x800023bc => Some (cycle_count_of_trace t' = 0)
| 0x800023c0 => Some (time_of_vListInitialiseItem t)
| _ => None
end | _ => None end.

  Theorem vListInitialiseItem_timing_gen :
    forall s t s' x' (base_mem : memory) (a0 : N)
      (ENTRY: startof t (x',s') = (Addr entry_addr, s))
      (MDL: models rvtypctx s)
      (A0: s R_A0 = a0),
    satisfies_all lifted_prog (timing_invs base_mem a0) exits ((x',s') :: t).
  Proof.
    Admitted.

End vListInitialiseItem_timing_gen_Proof.

Module vListInitialiseItem_timing_gen_CPU := NEORV32 NEORV32BaseConfig.
Module vListInitialiseItem_timing_gen_Concrete := vListInitialiseItem_timing_gen_Proof vListInitialiseItem_timing_gen_CPU.
